const params=new URLSearchParams(location.search);const breed=BREEDS.find(item=>item.id===params.get('breed'));const root=document.getElementById('profileRoot');
const labels={affection:'甘えん坊',cuddle:'抱っこ・密着',independence:'マイペース',play:'遊び好き',quiet:'静かめ',talk:'おしゃべり',care:'お手入れ軽め'};
const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
if(!breed){document.title='プロフィールが見つかりません｜猫好きのための比較サイト';root.innerHTML='<div class="wrap error"><h1>猫種が見つかりませんでした。</h1><p><a class="read" href="index.html">猫種図鑑へ戻る →</a></p></div>'}else{
document.title=`${breed.name}の性格・特徴｜猫種図鑑`;
document.querySelector('meta[name="description"]').setAttribute('content',`${breed.name}の一般的な性格、体格、被毛、お手入れ、暮らしとの相性を紹介します。`);
const distance=item=>Object.keys(labels).reduce((total,key)=>total+Math.abs(item.stats[key]-breed.stats[key]),0);
const related=[...BREEDS].filter(item=>item.id!==breed.id).sort((a,b)=>distance(a)-distance(b)).slice(0,4);
const mediaUrl=`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(breed.media.file)}?width=1200`;
root.innerHTML=`<div class="wrap breadcrumb"><a href="index.html">猫種図鑑</a> ／ ${escapeHtml(breed.name)}</div><section class="profile-hero"><div class="wrap profile-head"><span class="breed-mark" style="--breed:${breed.color}">${breed.mark}</span><div><div class="eyebrow">BREED PROFILE</div><h1>${escapeHtml(breed.name)}</h1><div class="profile-en">${escapeHtml(breed.en)}</div></div><figure class="profile-photo"><img src="${mediaUrl}" alt="${escapeHtml(breed.name)}の写真" fetchpriority="high"><figcaption><a href="${breed.media.page}" target="_blank" rel="noopener">写真：${escapeHtml(breed.media.author)}／${escapeHtml(breed.media.license)} ↗</a></figcaption></figure><p class="profile-summary">${escapeHtml(breed.summary)}</p></div></section><div class="wrap profile-main"><div><section class="profile-card"><h2>基本プロフィール</h2><div class="facts"><div class="fact"><span>SIZE</span><b>${escapeHtml(breed.size)}</b></div><div class="fact"><span>COAT</span><b>${escapeHtml(breed.coat)}</b></div><div class="fact"><span>ORIGIN</span><b>${escapeHtml(breed.origin)}</b></div></div><h3>性格の距離感</h3><p>${escapeHtml(breed.character)}</p><h3>一緒に暮らすイメージ</h3><p>${escapeHtml(breed.living)}</p></section><section class="profile-card"><h2>向きやすい暮らし</h2><ul class="profile-list">${breed.goodFor.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul><h3>日々のお手入れと環境</h3><ul class="profile-list">${breed.carePoints.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section><section class="profile-card"><h2>猫砂選びのヒント</h2><p>${escapeHtml(breed.litter)}</p><a class="back-guide" href="../index.html#cats">猫タイプ別の猫砂比較を見る<small>長毛・大型・子猫・多頭飼いなどから比較</small></a></section></div><aside><section class="profile-card"><h2>7つの傾向</h2><div class="trait-chart">${Object.entries(labels).map(([key,label])=>`<div class="trait-row"><span>${label}</span><span class="bar"><i style="--value:${breed.stats[key]*20}%"></i></span><b>${breed.stats[key]}</b></div>`).join('')}</div><p class="disclaimer">5段階の編集目安です。性格を保証するものではありません。</p></section><section class="profile-card"><h2>似た距離感の猫種</h2><div class="related-grid">${related.map(item=>`<a class="related-card" href="profile.html?breed=${item.id}"><b>${escapeHtml(item.name)}</b><br><span class="profile-en">${escapeHtml(item.en)}</span></a>`).join('')}</div></section><section class="profile-card"><h2>参照情報</h2><div class="source-list"><a href="${breed.source}" target="_blank" rel="noopener">猫種団体のプロフィール ↗</a><a href="media-credits.html">写真・動画素材のクレジット</a><a href="../editorial-policy.html">当サイトの編集方針</a></div><p class="disclaimer">最終確認日：2026年9月30日。猫種の傾向には大きな個体差があります。</p></section></aside></div>`;
}
